"""
DJI DRC Python SDK

简洁实用的 DJI 无人机远程控制工具包
"""

from .core import MQTTClient, ServiceCaller
from .services import (
    request_control_auth,
    release_control_auth,
    enter_drc_mode,
    exit_drc_mode,
    change_live_lens,
    start_live_push,
    stop_live_push,
    return_home,
    fly_to_point,
    start_heartbeat,
    stop_heartbeat,
    send_stick_control,
    set_camera_zoom,
    camera_screen_split,
    camera_screen_split_wait,
    drc_live_lens_change,
    drc_live_lens_change_wait,
    take_photo,
    take_photo_wait,
    camera_look_at,
    camera_aim,
    drone_emergency_stop,
    drone_emergency_stop_wait,
    reset_gimbal,
    setup_drc_connection,
    setup_multiple_drc_connections,
    DRCConnectionManager,
    ConnectionState,
    HeartbeatHandle,
)
from .utils import (
    print_json_message,
    get_key,
    wait_for_camera_data,
    build_video_id,
)
from .live_utils import (
    start_live,
    stop_live,
    set_live_quality,  # 使用带详细日志的版本
    zoom_control_loop,
)
from .primitives import (
    wait_for_condition,
    send_stick_repeatedly,
    fly_to_waypoint,
    monitor_flyto_progress,
)
from .gimbal import (
    DEFAULT_GIMBAL_PITCH_PROFILE,
    GIMBAL_PITCH_MAX_DEG,
    GIMBAL_PITCH_MIN_DEG,
    GimbalPitchCalibrationResult,
    GimbalPitchCalibrationSample,
    GimbalPitchCalibrationStatus,
    GimbalPitchController,
    GimbalPitchResult,
    GimbalPitchStatus,
    GimbalPitchTask,
    GimbalPitchTraceStep,
    build_calibrated_profile,
    calibrate_gimbal_pitch,
    classify_limit_or_failure,
    load_gimbal_pitch_profile,
    save_gimbal_pitch_profile,
    set_gimbal_pitch_async,
)
from .tasks import (
    MissionRunner,
    run_parallel_missions,
    cleanup_missions,
    create_takeoff_mission,
    load_trajectory,
    fly_trajectory_sequence,
    create_trajectory_mission,
    create_takeoff_table,
    create_trajectory_table,
)

__version__ = "1.0.0"

__all__ = [
    # Core
    "MQTTClient",
    "ServiceCaller",
    # Services
    "request_control_auth",
    "release_control_auth",
    "enter_drc_mode",
    "exit_drc_mode",
    "change_live_lens",
    "set_live_quality",
    "start_live_push",
    "stop_live_push",
    "return_home",
    "fly_to_point",
    "start_heartbeat",
    "stop_heartbeat",
    "send_stick_control",
    "set_camera_zoom",
    "camera_screen_split",
    "camera_screen_split_wait",
    "drc_live_lens_change",
    "drc_live_lens_change_wait",
    "take_photo",
    "take_photo_wait",
    "camera_look_at",
    "camera_aim",
    "drone_emergency_stop",
    "drone_emergency_stop_wait",
    "reset_gimbal",
    "setup_drc_connection",
    "setup_multiple_drc_connections",
    "DRCConnectionManager",
    "ConnectionState",
    "HeartbeatHandle",
    # Utils
    "print_json_message",
    "get_key",
    "wait_for_camera_data",
    "build_video_id",
    # Live Utils
    "start_live",
    "stop_live",
    "zoom_control_loop",
    # Primitives
    "wait_for_condition",
    "send_stick_repeatedly",
    "fly_to_waypoint",
    "monitor_flyto_progress",
    # Gimbal
    "DEFAULT_GIMBAL_PITCH_PROFILE",
    "GIMBAL_PITCH_MAX_DEG",
    "GIMBAL_PITCH_MIN_DEG",
    "GimbalPitchCalibrationResult",
    "GimbalPitchCalibrationSample",
    "GimbalPitchCalibrationStatus",
    "GimbalPitchController",
    "GimbalPitchResult",
    "GimbalPitchStatus",
    "GimbalPitchTask",
    "GimbalPitchTraceStep",
    "build_calibrated_profile",
    "calibrate_gimbal_pitch",
    "classify_limit_or_failure",
    "load_gimbal_pitch_profile",
    "save_gimbal_pitch_profile",
    "set_gimbal_pitch_async",
    # Tasks
    "MissionRunner",
    "run_parallel_missions",
    "cleanup_missions",
    "create_takeoff_mission",
    "load_trajectory",
    "fly_trajectory_sequence",
    "create_trajectory_mission",
    "create_takeoff_table",
    "create_trajectory_table",
]
